# True color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Clipboard
set -g set-clipboard on

# Scrollback
set -g history-limit 50000

# Mouse
set -g mouse on

# No ESC delay (neovim)
set -sg escape-time 0

# Focus events (neovim :checkhealth recommendation)
set -g focus-events on
